### ISSUE TITLE
Options to set log level for starting and finished

### ISSUE THREAD

**Issue by devth** [nberger/ring-logger#21]
Defining custom printers to do this is onerous for `starting` and especially for `finished`.

**Comment by nberger** [comment]
Thanks for reporting!

I see the difficulty in creating custom printers for those messages. Not sure what's a good way to pass those options (especially for `finished` because it might log an `info` or an `error` message), or how we can make it easier to create a custom printer for them. I have to think more about it.

**Comment by nberger** [comment]
Sorry for not coming back to this before. I never got around to finding a good way to solve this: I didn't want to add more customization options, it would start to be like a nightmare of bolts and switches so users would rather just override the printer multimethods. I think I found a way now and I explain it in [the issue about the future 0.8.x series](#30). If you are still interested on this, please take a look, any feedback would be appreciated. I'll close this issue now.
