### ISSUE TITLE
wrap-log-request-params doesn't work

### ISSUE THREAD

**Issue by awvalenti** [nberger/ring-logger#45]
It is simply ignored.

I'm running Clojure 1.10 on Linux Mint Cinnamon 19 64-bits.

I've tried all these:
```clojure
(defn -main
  [& args]
  (-> app
    logger/wrap-with-logger
    logger/wrap-log-request-params
    logger/wrap-log-request-start
    logger/wrap-log-response
    (run-jetty {:port (or (some-> args first Integer/parseInt) 3000)})))
```
```clojure
(defn -main
  [& args]
  (-> app
    logger/wrap-log-request-params
    (run-jetty {:port (or (some-> args first Integer/parseInt) 3000)})))
```
```clojure
(defn -main
  [& args]
  (-> app
    logger/wrap-with-logger
    logger/wrap-log-request-params
    (run-jetty {:port (or (some-> args first Integer/parseInt) 3000)})))
```
```clojure
(defn -main
  [& args]
  (-> app
    logger/wrap-log-request-params
    logger/wrap-log-request-start
    logger/wrap-log-response
    (run-jetty {:port (or (some-> args first Integer/parseInt) 3000)})))
```

**Comment by EricBoersma** [comment]
Also seeing this same issue. No matter what I do, I can't get request params to log at all.

**Comment by augusto-jm-amaral** [comment]
Same problem.

**Comment by joefromct** [comment]
Depending on what you are doing you probably need to add the `:request-keys` to include maybe `:body` for a post.  

Also, if you really want to see what's in body you'll probably have to slurp the content to get it visible as text.  Of course, this will have overhead so i'm only doing things like this in dev. 

Maybe something like this:

``` clojure
(defn compile-middleware [app]
  (-> app
      (logger/wrap-log-request-params {:log-fn (fn [{:keys [level throwable message]}]
                                                 (timbre/info level message throwable))
                                       :transform-fn #(-> %
                                                          (update-in  [:message :body] slurp)
                                                          clojure.pprint/pprint)
                                       :log-exceptions? true
                                       :log-level :info
                                       :request-keys  [:request-method :uri :server-name :headers :body]})
      maybe-wrap-basic-authentication
      maybe-wrap-reload))
```

**Comment by ericnormand** [comment]
It looks like you need to parse the query params (using [`ring.middleware.params/wrap-params`](https://ring-clojure.github.io/ring/ring.middleware.params.html#var-wrap-params)). Ring doesn't parse the query string by default.

**Comment by deobald** [comment]
`wrap-log-request-params` _does work_ but I just spent a minute battling with this because I had forgotten it makes some assumptions and doesn't (quite) work out-of-the-box. Here are the two thing you need to keep in mind:

1. **Middleware Order:** Make sure `wrap-params` happens before `wrap-log-request-params` in the middleware lifecycle. Remember the order is bottom-up if you're using the threading macro (`->`).
2. **Log Level:** By default, `wrap-log-request-params` logs to `:debug` and it's unlikely your local log config is set that high unless you're, well, debugging. Personally, I diagnose issues using param data all the time, so I bump the log level to `:info`.

### Examples of these two notes follow

1. **Middleware Order example**

This fails:

```clojure
  (-> (handler)
      wrap-log-response
      wrap-keyword-params
      wrap-params
      wrap-log-request-params    ;; FAILS: this happens too early in the middleware lifecycle
      wrap-log-request-start)
```

This succeeds:

```clojure
  (-> (handler)
      wrap-log-response
      wrap-log-request-params    ;; SUCCEEDS: the params have been parsed out of the request
      wrap-keyword-params
      wrap-params
      wrap-log-request-start)
```

2. **Log Level example**

You can either bump your log level to DEBUG or use `:transform-fn` to adjust the log level of params logging before it hits the `log-fn`. I prefer the latter, since DEBUG tends to be very noisy:

```clojure
(wrap-log-request-params {:transform-fn (fn [m] (assoc m :level :info))})
```

Hopefully this saves someone a minute or two. :)

@nberger I think you can close this issue. Maybe some of the resolving comments could go into the docs?

**Comment by nberger** [comment]
@deobald thanks for helping out here. You are correct, `wrap-log-request-params` depends on having `wrap-params` to parse the params first. That's what [the example](https://github.com/nberger/ring-logger/blob/d30e011f0f97afcd944e7a382195db7796ad1015/example/src/example/core.clj#L65-L67) does too.

I agree it would be great to put some of this into the docs. Unfortunately I'm not having too much time to actively maintain the project lately. I made you a collaborator in case you'd like to make those additions yourself.

Thanks!
