### ISSUE TITLE
Logging Request Body

### ISSUE THREAD

**Issue by bongolegend** [nberger/ring-logger#51]
Hi, thanks for working on this. Is there a way to log the request body? If so, I haven't been able to figure it out.

I expected to pass `:body` to the `:request-keys` option in `wrap-with-logger`, but this errors with ```com.fasterxml.jackson.core.JsonGenerationException: Cannot JSON encode object of class: class org.eclipse.jetty.server.HttpInputOverHTTP: HttpInputOverHTTP@1a03aea5[c=0,q=0,[0]=null,s=STREAM]```

Thanks.

**Comment by Kauko** [comment]
Hey, sorry for getting back to you so slowly. I got maintainer rights to this repo, but just forgot to change my email settings so I didn't get notified when you opened t his.

I think the library already does what you want by default. The parameters in the body are merged to the `:params` map. See the PR I've attached.

I'll close this issue since it's been so long since you opened it that I'm not sure if this is still even relevant. Feel free to open it again, or contact me in Clojurians Slack if I misunderstood you.
